substitutions:
  devicename: enbrighten1
  upper_devicename: Enbrighten1

esphome:
  name: $devicename

esp8266:
  board: esp_wroom_02

wifi:
  ssid: !secret ssid
  password: !secret ssid_password
  use_address: "$devicename.home"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $upper_devicename Hotspot
    #password: !secret ap_password

captive_portal:
logger:
api:
ota:


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      #mode: INPUT_PULLUP
    id: button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: $devicename

switch:
  - platform: gpio
    name: $devicename
    pin: GPIO12
    id: relay
    icon: "mdi:floor-lamp"

    on_turn_on:
      - output.turn_on: switch_led
    on_turn_off:
      - output.turn_off: switch_led


output:
  - platform: gpio
    pin: GPIO4
    id: switch_led
    inverted: yes

